all: agenciaA_cliente agenciaB_cliente  server 
.PHONY:all


agenciaA_cliente : agenciaA_cliente.c
	gcc -o agenciaA_cliente agenciaA_cliente.c

agenciaB_cliente : agenciaB_cliente.c
	gcc -o agenciaB_cliente agenciaB_cliente.c


server : server.c 
	gcc -o server server.c 

